name: pullrequest

on:
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Maven Package
        run: mvn -B clean install

      - name: Generate jacoco badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/


      
      
